import { useEffect, useMemo, useState, type ChangeEvent } from 'react'
import './App.css'
import type { GoalTargets, TrackerData, Shift } from './types'
import { STORAGE_KEY, dateFormat, dateOnly, dayNames, formatTime, getPeriodStart, hoursFor, loadData, makeWeek, money, restoreData } from './lib/tracker'

function App() {
  const [data, setData] = useState<TrackerData>(loadData)
  const [tab, setTab] = useState<'dashboard' | 'tracker'>('dashboard')
  const [editingWeek, setEditingWeek] = useState<string | null>(null)
  const [addingWeek, setAddingWeek] = useState(false)
  const [newWeekStart, setNewWeekStart] = useState('')
  const [newWeekEnd, setNewWeekEnd] = useState('')
  const [goalSlide, setGoalSlide] = useState(0)
  const [goalEditorOpen, setGoalEditorOpen] = useState(false)
  const [goalDraft, setGoalDraft] = useState<GoalTargets>(() => data.goals)
  const [currentTime] = useState(() => Date.now())
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
    } catch { /* keep the in-memory tracker usable if browser storage is unavailable */ }
  }, [data])

  const allWeeks = useMemo(() => [data.activeWeek, ...data.archivedWeeks], [data])
  const totalHours = allWeeks.reduce((sum, week) => sum + week.shifts.reduce((weekSum, shift) => weekSum + hoursFor(shift), 0), 0)
  const activeHours = data.activeWeek.shifts.reduce((sum, shift) => sum + hoursFor(shift), 0)
  const totalEarnings = totalHours * data.wage
  const biweeklyEarnings = allWeeks.slice(0, 2).reduce((sum, week) => sum + week.shifts.reduce((weekSum, shift) => weekSum + hoursFor(shift), 0), 0) * data.wage
  const goalStart = data.targetStartDate ? new Date(`${data.targetStartDate}T00:00:00`).getTime() : currentTime
  const countdownBase = Math.max(currentTime, goalStart)
  const targetDays = data.targetDate ? Math.max(0, Math.ceil((new Date(`${data.targetDate}T23:59:59`).getTime() - countdownBase) / 86400000)) : 0
  const countdownWeeks = Math.floor(targetDays / 7)
  const countdownDays = targetDays % 7
  const goalOptions = [
    { key: 'week' as const, label: 'This week', amount: activeHours * data.wage, color: '#6f9f72' },
    { key: 'biweekly' as const, label: 'Biweekly', amount: biweeklyEarnings, color: '#d28a59' },
    { key: 'semester' as const, label: 'Semester', amount: totalEarnings, color: '#6e83ad' },
  ]
  const selectedGoal = goalOptions[goalSlide]
  const selectedTarget = data.goals[selectedGoal.key]
  const selectedProgress = selectedTarget > 0 ? Math.min(100, selectedGoal.amount / selectedTarget * 100) : 0
  const maxNewWeekEnd = (() => {
    if (!newWeekStart) return undefined
    const date = new Date(`${newWeekStart}T00:00:00Z`)
    date.setUTCDate(date.getUTCDate() + 6)
    return date.toISOString().slice(0, 10)
  })()

  const updateActiveShift = (index: number, key: 'start' | 'end', value: string) => setData((current) => ({ ...current, activeWeek: { ...current.activeWeek, shifts: current.activeWeek.shifts.map((shift, shiftIndex) => shiftIndex === index ? { ...shift, [key]: value, hours: undefined, hoursInput: undefined } : shift) } }))
  const updateActiveHours = (index: number, value: string) => setData((current) => ({ ...current, activeWeek: { ...current.activeWeek, shifts: current.activeWeek.shifts.map((shift, shiftIndex) => shiftIndex === index ? { ...shift, hours: undefined, hoursInput: value } : shift) } }))
  const updateArchivedShift = (weekId: string, index: number, key: 'start' | 'end', value: string) => setData((current) => ({ ...current, archivedWeeks: current.archivedWeeks.map((week) => week.id !== weekId ? week : { ...week, shifts: week.shifts.map((shift, shiftIndex) => shiftIndex === index ? { ...shift, [key]: value, hours: undefined, hoursInput: undefined } : shift) }) }))
  const updateArchivedHours = (weekId: string, index: number, value: string) => setData((current) => ({ ...current, archivedWeeks: current.archivedWeeks.map((week) => week.id !== weekId ? week : { ...week, shifts: week.shifts.map((shift, shiftIndex) => shiftIndex === index ? { ...shift, hours: undefined, hoursInput: value } : shift) }) }))
  const archiveCurrentWeek = () => setData((current) => { const nextPeriod = getPeriodStart(new Date(Date.now() + 86400000), current.weekStartDay, current.resetTime); const alreadyArchived = current.archivedWeeks.some((week) => week.id === current.activeWeek.id); return { ...current, archivedWeeks: alreadyArchived ? current.archivedWeeks : [current.activeWeek, ...current.archivedWeeks], activeWeek: makeWeek(nextPeriod, current.weekStartDay) } })
  const addPastWeek = () => {
    if (!newWeekStart || !newWeekEnd || newWeekEnd < newWeekStart) return
    const start = new Date(`${newWeekStart}T00:00:00`)
    const end = new Date(start)
    end.setDate(end.getDate() + 6)
    const shifts: Shift[] = []
    for (let index = 0; index < 7; index += 1) {
      const date = new Date(start)
      date.setDate(date.getDate() + index)
      shifts.push({ day: dayNames[date.getDay()], date: dateOnly(date), start: '', end: '' })
    }
    setData((current) => current.archivedWeeks.some((week) => week.id === newWeekStart) || current.activeWeek.id === newWeekStart ? current : { ...current, archivedWeeks: [{ id: newWeekStart, startDate: newWeekStart, label: `${dateFormat.format(start)} - ${dateFormat.format(end)}`, shifts }, ...current.archivedWeeks] })
    setNewWeekStart('')
    setNewWeekEnd('')
    setAddingWeek(false)
  }
  const deleteArchivedWeek = (weekId: string) => setData((current) => ({ ...current, archivedWeeks: current.archivedWeeks.filter((week) => week.id !== weekId) }))
  const updateSchedule = (key: 'weekStartDay' | 'resetTime', value: string) => setData((current) => ({ ...current, [key]: key === 'weekStartDay' ? Number(value) : value }))
  const exportData = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'finance-tracker-backup.json'; link.click(); URL.revokeObjectURL(url) }
  const importData = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(String(reader.result)) as Partial<TrackerData>; if (imported.activeWeek && Array.isArray(imported.archivedWeeks)) setData(restoreData(imported)) } catch { /* ignore invalid backups */ } }; reader.readAsText(file); event.target.value = '' }
  const openGoalEditor = () => { setGoalDraft(data.goals); setGoalEditorOpen(true) }
  const saveGoals = () => { setData((current) => ({ ...current, goals: { week: Math.max(0, goalDraft.week || 0), biweekly: Math.max(0, goalDraft.biweekly || 0), semester: Math.max(0, goalDraft.semester || 0) } })); setGoalEditorOpen(false) }
  const activeEditingWeek = editingWeek ? allWeeks.find((week) => week.id === editingWeek) : null

  return (
    <main className="app-shell">
      <header className="topbar"><div className="brand-mark">FT</div><div><p className="eyebrow"></p><h1>Finance &amp; Time</h1></div><div className="topbar-right"><span className="saved-state">Saved locally</span><div className="avatar">A</div></div></header>
      <nav className="tabs" aria-label="Primary navigation"><button className={tab === 'dashboard' ? 'tab active' : 'tab'} onClick={() => setTab('dashboard')}>Dashboard</button><button className={tab === 'tracker' ? 'tab active' : 'tab'} onClick={() => setTab('tracker')}>Weekly HR Track</button></nav>

      {tab === 'tracker' ? <section className="page-content">
        <div className="page-heading"><div><p className="eyebrow accent-text">ACTIVE PERIOD</p><h2>Keep the week moving.</h2><p className="muted">Log your hours as you go. Your earnings update automatically.</p></div><button className="secondary-button" onClick={archiveCurrentWeek}>Archive week</button></div>
        <div className="summary-strip"><div><span className="summary-label">Current period</span><strong>{data.activeWeek.label}</strong></div><div><span className="summary-label">Hours logged</span><strong>{activeHours.toFixed(2)} <small>/ 40 hrs</small></strong></div><div><span className="summary-label">Estimated pay</span><strong>{money.format(activeHours * data.wage)}</strong></div><div><label className="summary-label" htmlFor="wage-input">Hourly wage</label><input id="wage-input" className="summary-input" type="number" min="0" step="0.25" value={data.wage || ''} placeholder="0.00" onChange={(event) => setData((current) => ({ ...current, wage: Number(event.target.value) }))} /></div></div>
        <div className="section-title"><div><h3>Daily shifts</h3><p className="muted">{data.activeWeek.shifts[0].day} through {data.activeWeek.shifts[6].day}</p></div><span className="live-badge"><i /> Live</span></div>
        <div className="shift-table"><div className="table-head"><span>Day</span><span>Start time</span><span>End time</span><span>Hours</span><span>Est. earnings</span></div>{data.activeWeek.shifts.map((shift, index) => <div className="table-row" key={shift.date}><div className="day-cell"><strong>{shift.day}</strong><span>{dateFormat.format(new Date(`${shift.date}T12:00:00`))}</span></div><input aria-label={`${shift.day} start time`} type="text" inputMode="text" placeholder="9:00 AM" value={shift.start} onChange={(event) => updateActiveShift(index, 'start', event.target.value)} onBlur={(event) => updateActiveShift(index, 'start', formatTime(event.target.value))} /><input aria-label={`${shift.day} end time`} type="text" inputMode="text" placeholder="5:00 PM" value={shift.end} onChange={(event) => updateActiveShift(index, 'end', event.target.value)} onBlur={(event) => updateActiveShift(index, 'end', formatTime(event.target.value))} /><input aria-label={`${shift.day} hours`} className="hours-input" type="text" inputMode="decimal" pattern="[0-9]*[.]?[0-9]*" placeholder="0.00" value={shift.hoursInput ?? (typeof shift.hours === 'number' ? String(shift.hours) : '')} onFocus={(event) => event.currentTarget.select()} onChange={(event) => updateActiveHours(index, event.target.value)} /><span className="earnings-cell">{money.format(hoursFor(shift) * data.wage)}</span></div>)}</div>
        <div className="tracker-footer"><span>Week total</span><strong>{activeHours.toFixed(2)} hrs</strong><strong>{money.format(activeHours * data.wage)}</strong></div>
        <div className="settings-row"><label>Goal start date<input type="date" value={data.targetStartDate} onChange={(event) => setData((current) => ({ ...current, targetStartDate: event.target.value }))} /></label><label>Goal end date<input type="date" value={data.targetDate} onChange={(event) => setData((current) => ({ ...current, targetDate: event.target.value }))} /></label><label>Week starts<select value={data.weekStartDay} onChange={(event) => updateSchedule('weekStartDay', event.target.value)}>{dayNames.map((day, index) => <option value={index} key={day}>{day}</option>)}</select></label><label>Reset time<input type="time" value={data.resetTime} onClick={(event) => event.currentTarget.showPicker?.()} onChange={(event) => updateSchedule('resetTime', event.target.value)} /></label><div className="reset-note"><span className="calendar-icon">R</span><span><strong>Weekly reset</strong><small>Archives on {dayNames[data.weekStartDay]} at {data.resetTime}</small></span></div></div>
        <div className="data-tools"><strong>Private browser data</strong><span>Stored only on this device.</span><button className="text-button" onClick={exportData}>Export backup</button><label className="text-button">Import backup<input className="file-input" type="file" accept="application/json" onChange={importData} /></label></div>
      </section> : <section className="page-content dashboard-page">
        <div className="page-heading"><div><p className="eyebrow accent-text">YOUR OVERVIEW</p><h2>Make your time count.</h2><p className="muted">A clear view of where your work is taking you.</p></div><button className="secondary-button" onClick={() => setTab('tracker')}>Log hours</button></div>
        <div className="metric-grid"><article className="metric-card featured"><span className="metric-label">Total earned</span><strong>{money.format(totalEarnings)}</strong><span className="metric-foot">Across {allWeeks.length} {allWeeks.length === 1 ? 'week' : 'weeks'}</span></article><article className="metric-card"><span className="metric-label">Total hours</span><strong>{totalHours.toFixed(2)}</strong><span className="metric-foot">Hours worked</span></article><article className="metric-card"><span className="metric-label">Goal countdown</span><strong>{data.targetDate ? countdownWeeks : '--'}<small>{data.targetDate ? `w ${countdownDays}d` : ' Set a date'}</small></strong><span className="metric-foot">{data.targetDate ? `Until ${dateFormat.format(new Date(`${data.targetDate}T12:00:00`))}` : 'Choose a goal end date'}</span></article></div>
        <div className="dashboard-grid"><section className="panel goal-ring-panel"><div className="section-title"><div><span className="metric-label">Savings targets</span><h3>{selectedGoal.label}</h3></div><button className="text-button" onClick={openGoalEditor}>{selectedTarget > 0 ? 'Edit goals' : 'Set goals'}</button></div><div className="goal-slide"><div className="goal-ring" style={{ background: `conic-gradient(${selectedGoal.color} ${selectedProgress}%, #d4ddd6 0)` }}><div className="goal-ring-center"><strong>{money.format(selectedGoal.amount)}</strong><span>earned so far</span><small>{selectedTarget > 0 ? `${Math.round(selectedProgress)}% of ${money.format(selectedTarget)}` : 'Set a target to begin'}</small></div></div><div className="goal-slide-copy"><p className="muted">{selectedGoal.key === 'week' ? 'Your current weekly target' : selectedGoal.key === 'biweekly' ? 'Your current two-week target' : 'Your semester target'}</p><div className="goal-dots" aria-label="Goal period selector">{goalOptions.map((goal, index) => <button key={goal.key} className={index === goalSlide ? 'goal-dot active' : 'goal-dot'} style={{ background: goal.color }} aria-label={`Show ${goal.label} goal`} onClick={() => setGoalSlide(index)} />)}</div><div className="goal-periods">{goalOptions.map((goal, index) => <button key={goal.key} className={index === goalSlide ? 'goal-period active' : 'goal-period'} onClick={() => setGoalSlide(index)}>{goal.label}</button>)}</div></div></div></section><section className="panel goal-panel"><span className="metric-label">Semester goal</span><h3>{data.targetDate ? dateFormat.format(new Date(`${data.targetDate}T12:00:00`)) : 'No date set'}</h3><p className="goal-countdown-copy">{data.targetDate ? `Semester ends in ${targetDays} days` : 'Set a semester end date'}</p><p className="muted">{data.targetStartDate ? `Started ${dateFormat.format(new Date(`${data.targetStartDate}T12:00:00`))}` : 'Choose a semester start date'}{data.targetDate ? ` · Ends ${dateFormat.format(new Date(`${data.targetDate}T12:00:00`))}` : ''}</p><div className="countdown"><strong>{data.targetDate ? countdownWeeks : '--'}</strong><span>weeks</span><strong>{data.targetDate ? countdownDays : '--'}</strong><span>days</span></div><div className="progress-track"><div style={{ width: `${Math.min(100, totalEarnings / 1000 * 100)}%` }} /></div><small className="muted">{money.format(totalEarnings)} toward your tracked total</small></section></div>
        <section className="panel history-panel"><div className="section-title"><div><h3>Weeks</h3><p className="muted">Your current week and archived history.</p></div><div className="history-actions"><button className="text-button" onClick={() => setAddingWeek(true)}>+ Add past week</button><button className="text-button" onClick={() => setTab('tracker')}>View active week</button></div></div><div className="history-row current-week-row"><span><strong>Current week</strong><small>{data.activeWeek.label} · {activeHours.toFixed(2)} hours</small></span><strong>{money.format(activeHours * data.wage)}</strong><span className="current-badge">ACTIVE</span><button className="edit-button" onClick={() => setTab('tracker')}>Edit</button></div>{data.archivedWeeks.length === 0 ? <div className="empty-history">Your archived weeks will appear here after your first reset.</div> : data.archivedWeeks.map((week) => { const weekHours = week.shifts.reduce((sum, shift) => sum + hoursFor(shift), 0); return <div className="history-row" key={week.id}><span><strong>{week.label}</strong><small>{weekHours.toFixed(2)} hours</small></span><strong>{money.format(weekHours * data.wage)}</strong><button className="edit-button" onClick={() => setEditingWeek(week.id)}>Edit</button><button className="delete-button" onClick={() => deleteArchivedWeek(week.id)}>Delete</button></div> })}</section>
      </section>}

      {addingWeek && <div className="modal-backdrop" onClick={() => setAddingWeek(false)}><div className="modal small-modal" onClick={(event) => event.stopPropagation()}><div className="section-title"><div><p className="eyebrow accent-text">HISTORICAL WEEK</p><h3>Add a past week</h3></div><button className="close-button" onClick={() => setAddingWeek(false)}>X</button></div><p className="muted modal-copy">Choose the start and end dates. The blank period will be added to your archive for editing.</p><div className="date-pair"><label className="modal-date-label">Week start<input type="date" value={newWeekStart} onChange={(event) => setNewWeekStart(event.target.value)} /></label><label className="modal-date-label">Week end<input type="date" min={newWeekStart} max={maxNewWeekEnd} value={newWeekEnd} onChange={(event) => setNewWeekEnd(event.target.value)} /></label></div><div className="modal-actions"><button className="secondary-button" onClick={() => setAddingWeek(false)}>Cancel</button><button className="primary-button" disabled={!newWeekStart || !newWeekEnd || newWeekEnd < newWeekStart || (maxNewWeekEnd !== undefined && newWeekEnd > maxNewWeekEnd)} onClick={addPastWeek}>Add week</button></div></div></div>}
      {goalEditorOpen && <div className="modal-backdrop" onClick={() => setGoalEditorOpen(false)}><div className="modal small-modal" onClick={(event) => event.stopPropagation()}><div className="section-title"><div><p className="eyebrow accent-text">SAVINGS TARGETS</p><h3>Set your goals</h3></div><button className="close-button" onClick={() => setGoalEditorOpen(false)}>X</button></div><p className="muted modal-copy">Choose how much you want to earn in each period. Your circles update as you log hours.</p>{goalOptions.map((goal) => <label className="goal-input-label" key={goal.key}><span><i style={{ background: goal.color }} />{goal.label}</span><input type="number" min="0" step="25" placeholder="0.00" value={goalDraft[goal.key] || ''} onChange={(event) => setGoalDraft((current) => ({ ...current, [goal.key]: Number(event.target.value) }))} /></label>)}<div className="modal-actions"><button className="secondary-button" onClick={() => setGoalEditorOpen(false)}>Cancel</button><button className="primary-button" onClick={saveGoals}>Save goals</button></div></div></div>}
      {activeEditingWeek && <div className="modal-backdrop" onClick={() => setEditingWeek(null)}><div className="modal" onClick={(event) => event.stopPropagation()}><div className="section-title"><div><p className="eyebrow accent-text">HISTORICAL EDIT</p><h3>{activeEditingWeek.label}</h3></div><button className="close-button" onClick={() => setEditingWeek(null)}>X</button></div><div className="modal-shifts">{activeEditingWeek.shifts.map((shift, index) => <div className="modal-row" key={shift.date}><span>{shift.day}</span><input type="text" inputMode="text" placeholder="9:00 AM" aria-label={`${shift.day} historical start time`} value={shift.start} onChange={(event) => updateArchivedShift(activeEditingWeek.id, index, 'start', event.target.value)} onBlur={(event) => updateArchivedShift(activeEditingWeek.id, index, 'start', formatTime(event.target.value))} /><input type="text" inputMode="text" placeholder="5:00 PM" aria-label={`${shift.day} historical end time`} value={shift.end} onChange={(event) => updateArchivedShift(activeEditingWeek.id, index, 'end', event.target.value)} onBlur={(event) => updateArchivedShift(activeEditingWeek.id, index, 'end', formatTime(event.target.value))} /><input type="text" inputMode="decimal" pattern="[0-9]*[.]?[0-9]*" aria-label={`${shift.day} historical hours`} className="hours-input" placeholder="0.00" value={shift.hoursInput ?? (typeof shift.hours === 'number' ? String(shift.hours) : '')} onFocus={(event) => event.currentTarget.select()} onChange={(event) => updateArchivedHours(activeEditingWeek.id, index, event.target.value)} /></div>)}</div><button className="primary-button full-button" onClick={() => setEditingWeek(null)}>Done editing</button></div></div>}
    </main>
  )
}

export default App
